dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake-3.13
      - valgrind
      - libgtest-dev
      - g++
      - lcov

#install:
#  - cd /usr/src/gtest
#  - sudo cmake CMakeLists.txt
#  - sudo make
#  - sudo cp *.a /usr/lib
#  - cd /home/travis/build/TimFoxers/adv_cpp_2021_homework_1

script:
  - mkdir build && cd build && cmake .. && make
  - ls -l