name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
        
      - uses: actions/checkout@v2

      - name: installing c++/c compiler
        run: sudo apt install build-essential

      - name: installing git
        run: sudo apt install git

      - name: installing lcov
        run: sudo apt install lcov

      - name: installing valgrind
        run: sudo apt install valgrind

      - name: build
        run: mkdir build && cd build && cmake .. && make

      - name: tests
        run: ./build/tests
