name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: installing c++/c compiler
        run: sudo apt install build-essential

      - name: installing git
        run: sudo apt install git

      - name: installing lcov
        run: sudo apt install lcov

      - name: installing valgrind
        run: sudo apt install valgrind

      - name: build
        run: mkdir build && cd build && cmake .. && make

      - name: tests
        run: ./build/tests

      - name: get code coverage
        run: cd build/CMakeFiles/tests.dir/src && gcov *.gcno && lcov --capture --directory . --output-file test.info && mkdir coverage && genhtml test.info --output-directory coverage

      - name: coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: build/CMakeFiles/tests.dir/src/coverage